# Generated by Django 6.0.2 on 2026-02-19 09:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('coushout_to', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_account', to='accountsapp.accounts')),
            ],
        ),
    ]
