# Generated by Django 6.0.2 on 2026-02-24 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_cashout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashin',
            name='account',
        ),
        migrations.CreateModel(
            name='Ledgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accountsapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='MaineDiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('maine_diye', models.IntegerField(default=0)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainediye', to='accountsapp.ledgers')),
            ],
        ),
        migrations.CreateModel(
            name='MaineLiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('maine_liye', models.IntegerField(default=0)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maineliye', to='accountsapp.ledgers')),
            ],
        ),
        migrations.CreateModel(
            name='ManineDiyeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maine_diye/')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_diye', to='accountsapp.mainediye')),
            ],
        ),
        migrations.CreateModel(
            name='ManineLiyeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maine_liye/')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_liye', to='accountsapp.mainediye')),
            ],
        ),
        migrations.DeleteModel(
            name='CashOut',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='CashIn',
        ),
    ]
