# Generated by Django 6.0.2 on 2026-02-28 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_from', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('expensetracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiced', to='projectsapp.expensetracker')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='received_image/')),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_images', to='projectsapp.received')),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_to', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('expensetracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend', to='projectsapp.expensetracker')),
            ],
        ),
        migrations.CreateModel(
            name='SpendImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spend_image/')),
                ('spend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_images', to='projectsapp.spend')),
            ],
        ),
    ]
