# Generated by Django 6.0.2 on 2026-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
        migrations.AddField(
            model_name='spend',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
    ]
